# Generated by Django 5.0.3 on 2024-04-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieRatingApp', '0003_ratemovie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmovie',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
    ]
