# Generated by Django 5.0.3 on 2024-04-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieRatingApp', '0004_alter_addmovie_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmovie',
            name='rating',
            field=models.CharField(max_length=10),
        ),
    ]
