# Generated by Django 5.0.3 on 2024-04-03 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0002_userprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='username',
            new_name='name',
        ),
    ]
